<?php
namespace app\api\controller;

use app\api\controller\Common;
use app\common\lib\Alisms;
use app\common\lib\IAuth;
use app\common\model\User;
use think\controller;
use app\common\lib\exception\ApiException;

/*
 * 登陆权限基础类库，需要每个接口继承
 */

class AuthBase extends Common
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

    }

    public function isLogin()
    {
        $param = input('param.');
        if(empty($param['token'])){
            return false;
        }

        ;
    }
}
